export const SOCKET_EVENT_ENUM = {
  SOCKET_ERROR_EVENT: "SOCKET_ERROR_EVENT",
  RIDE_CREATED: "RIDE_CREATED",
  RIDE_BID_ACCEPTED: "RIDE_BID_ACCEPTED",
  RIDE_BID_REJECTED: "RIDE_BID_REJECTED",
  RIDE_UPDATE_MESSAGE: "RIDE_UPDATE_MESSAGE",
  MONEY_TRANSFER_UPDATE: "MONEY_TRANSFER_UPDATE",
  MONEY_ACCEPT_UPDATE: "MONEY_ACCEPT_UPDATE",
  PAYMENT_SENT: "PAYMENT_SENT",
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
  NEW_BID_CREATED: "NEW_BID_CREATED",
  BID: {
    BID_CREATED: "BID_CREATED",
    BID_UPDATED: "BID_UPDATED",
    BID_CANCELED: "BID_CANCELED",
  },
  CHAT: {
    NEW_CHAT_EVENT: "NEW_CHAT_EVENT",
    MESSAGE_RECEIVED_EVENT: "MESSAGE_RECEIVED_EVENT",
    CHAT_DELETE_EVENT: "CHAT_DELETE_EVENT",
  },
  BOOKING: {
    BOOKING_CREATED: "BOOKING_CREATED",
    BOOKING_ACCEPTED: "BOOKING_ACCEPTED",
    BOOKING_UPDATED: "BOOKING_UPDATED",
    BOOKING_CANCELLED: "BOOKING_CANCELLED",
    BOOKING_COMPLETED: "BOOKING_COMPLETED",
    BOOKING_DELETED: "BOOKING_DELETED",
  },
  DRIVER: {
    DRIVER_ONLINE: "DRIVER_ONLINE",
    DRIVER_OFFLINE: "DRIVER_OFFLINE",
    DRIVER_PROFILE_UPDATED: "DRIVER_PROFILE_UPDATED",
  },
  REQUEST: {
    NEW_REQUEST: "NEW_REQUEST",
    REQUEST_UPDATED: "REQUEST_UPDATED",
    REQUEST_CANCELLED: "REQUEST_CANCELLED",
  },
  WITHDRAWAL: {
    WITHDRAWAL_REQUESTED: "WITHDRAWAL_REQUESTED",
    WITHDRAWAL_PROCESSED: "WITHDRAWAL_PROCESSED",
  },
  WALLET: {
    TRANSACTION: "WALLET_TRANSACTION",
  },
  CONTACT_US: {
    NEW_CONTACT_US: "NEW_CONTACT_US",
    CONTACT_US_UPDATED: "CONTACT_US_UPDATED",
  },
};

export enum SOCKET_ROOM_ENUM {
  ADMIN_ROOM = "ADMIN_ROOM",
  USER_ROOM = "USER_ROOM",
  DRIVER_ROOM = "DRIVER_ROOM",
}
